<template>
	<div class="footer">
   <!-- footer-->
    <footer>
      <div class="wrapper">
        <p>&copy; Copyright 2017 - hamit.work</p>
        <ul class="social">
          <li><a target="_blank" href="https://www.github.com/tokayhamit"><img src="../assets/img/github.svg" alt="Github" title="Github"/></a></li>
          <li><a target="_blank" href="https://www.dribbble.com/hamittokay"><img src="../assets/img/dribbble.svg" alt="Dribbble" title="Dribbble"/></a></li>
          <li><a target="_blank" href="https://www.behance.net/hamittokay"><img src="../assets/img/behance.svg" alt="Behance" title="Behance"/></a></li>
        </ul>
      </div>
    </footer> 
  </div>
</template>

<script>
export default {
	name: 'FooterItem'
}
</script>